#!/bin/bash

# NOTIFICATIONS_COMMANDS.sh
# Commandes pratiques pour gérer le système de notifications

echo "🔔 Commandes du Système de Notifications"
echo "========================================"
echo ""

# ============ MIGRATIONS ============
echo "📊 MIGRATIONS & BASE DE DONNÉES"
echo "================================"
echo ""
echo "Créer la migration:"
echo "$ npx prisma migrate dev --name add_notifications"
echo ""
echo "Pusher le schéma directement:"
echo "$ npx prisma db push"
echo ""
echo "Voir Prisma Studio:"
echo "$ npx prisma studio"
echo ""

# ============ INSTALLATION ============
echo "📦 INSTALLATION"
echo "==============="
echo ""
echo "Backend:"
echo "$ npm install firebase-admin"
echo ""
echo "Frontend (Flutter):"
echo "$ flutter pub add firebase_messaging"
echo ""

# ============ CONFIGURATION ============
echo "⚙️  CONFIGURATION"
echo "================="
echo ""
echo "1. Télécharger clé de service Firebase:"
echo "   Firebase Console > Project Settings > Service Accounts > Generate New Private Key"
echo ""
echo "2. Ajouter à .env:"
echo "   FIREBASE_SERVICE_ACCOUNT_KEY='{...}'"
echo ""
echo "3. Ou utiliser le chemin du fichier:"
echo "   GOOGLE_APPLICATION_CREDENTIALS='/path/to/serviceAccountKey.json'"
echo ""

# ============ DÉVELOPPEMENT ============
echo "🚀 DÉVELOPPEMENT"
echo "==============="
echo ""
echo "Démarrer le backend avec orchestrateur:"
echo "$ npm run dev"
echo ""
echo "Tester les notifications:"
echo "$ node EXAMPLES.js"
echo ""

# ============ VÉRIFICATIONS ============
echo "✅ VÉRIFICATIONS"
echo "================"
echo ""
echo "Vérifier les tokens enregistrés:"
echo "$ sqlite3 database.db \"SELECT * FROM FCMToken WHERE isActive = true LIMIT 5;\""
echo ""
echo "Vérifier les notifications envoyées:"
echo "$ sqlite3 database.db \"SELECT COUNT(*) FROM Notification WHERE isSent = true;\""
echo ""
echo "Vérifier les non-lues:"
echo "$ sqlite3 database.db \"SELECT COUNT(*) FROM Notification WHERE isRead = false;\""
echo ""

# ============ LOGS ============
echo "📝 LOGS"
echo "======"
echo ""
echo "Backend notifications:"
echo "$ tail -f logs/notifications.log"
echo ""
echo "Flutter/App logs:"
echo "$ flutter logs | grep -i notification"
echo ""

# ============ TROUBLESHOOTING ============
echo "🐛 TROUBLESHOOTING"
echo "=================="
echo ""
echo "Vérifier que Firebase est initialisé:"
echo "- Lancer l'app et accepter les permissions"
echo "- Regarder la console pour \"FCM Token: ...\""
echo ""
echo "Si pas de permissions sur iOS:"
echo "- Vérifier Info.plist pour NSUserNotificationUsageDescription"
echo ""
echo "Si pas de permissions sur Android:"
echo "- Vérifier AndroidManifest.xml pour permissions"
echo ""
echo "Si tokens ne s'enregistrent pas:"
echo "- Vérifier que /api/notifications/register-fcm retourne 201"
echo "- Vérifier les logs du backend"
echo ""

# ============ INTÉGRATION ============
echo "🔗 INTÉGRATION DANS LES CONTRÔLEURS"
echo "==================================="
echo ""
echo "Exemple: Réservation créée"
echo "---"
echo "const { notificationsService, notificationOrchestrator } = require('../services');"
echo ""
echo "async createReservation(req, res) {"
echo "  const reservation = await create(...);"
echo ""
echo "  // Notifier confirmément"
echo "  await notificationsService.notifyReservationConfirmation(reservation.id);"
echo ""
echo "  res.status(201).json(reservation);"
echo "}"
echo ""

# ============ PRODUCTION ============
echo "🌍 PRODUCTION"
echo "============="
echo ""
echo "Checklist avant déploiement:"
echo "☐ Firebase configuré (serviceAccountKey)"
echo "☐ Variables d'env définies"
echo "☐ Migrations exécutées"
echo "☐ Orchestrateur configuré au boot"
echo "☐ Rate limiting activé"
echo "☐ Monitoring en place"
echo "☐ Logs centralisés"
echo "☐ Tests de notification fonctionnels"
echo ""

echo "✨ Pour plus d'info, voir NOTIFICATIONS_SETUP.md"
echo ""
